<?php /**@var \Shurik\QuickOrder\Block\QuickOrder $block */ ?>

<?php $productSku = $block->getProductSku()?>
<button type="submit"
        title="<?= $block->escapeHtml(__('Quick Order')) ?>"
        class="btn-btn-primary"
        id="btn-btn-primary<?=$productSku ?>"
>
    <span><?= /* @escapeNotVerified */ __('Quick Order') ?></span>
</button>



<div class="mypopup<?= $productSku ?>">
    <form action="<?= $block->getUrl("shurikquickorder/index/save") ?>"
          method="POST"
          data-mage-init='{"validation":{}}'>
        <label>Name
            <input type="text" name="name" data-validate='{"required":true, "maxlength": 18}'>
        </label>
        <label>Phone number
            <input type="number" name="phone" data-validate='{"required":true, "maxlength": 20, "number": true}'>
        </label>
        <label>Email
            <input type="email" name="email" data-validate="{'maxlength': 50, 'validate-email':true }">
        </label>
        <input type="hidden" name="sku" value="<?= $productSku ?>">
        <input type="hidden" name="url" value="<?= $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])?>">
        <input type="submit" value="Send" class="action submit primary">
    </form>
</div>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($,modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Quick Order',
                buttons: false
            };
            var popup = modal(options, $('.mypopup<?= $productSku ?>'));
            $("#btn-btn-primary<?=$productSku?>").on("click",function(){
                $('.mypopup<?= $productSku ?>').modal('openModal');
            });
        }
    );
</script>

